from pydantic import BaseModel, Field, ConfigDict
from typing import Dict, Any, Optional

class AIRequest(BaseModel):
    model_config = ConfigDict(frozen=True)

    request_id: str = Field(description="Unique correlation ID generated by the Decision Engine")
    prompt_name: str = Field(description="Name of the prompt capability queried")
    prompt_version: str = Field(description="Version string of the query prompt")
    context: Dict[str, Any] = Field(description="Normalized input context dictionary")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Custom diagnostic parameters")

class TokenUsage(BaseModel):
    model_config = ConfigDict(frozen=True)

    input_tokens: int = Field(description="Estimated or returned prompt tokens count")
    output_tokens: int = Field(description="Estimated or returned completion tokens count")
    total_tokens: int = Field(description="Sum of input and output tokens")
    estimated_cost: float = Field(description="Calculated cost of API call in USD")

class AIResponse(BaseModel):
    model_config = ConfigDict(frozen=True)

    request_id: str = Field(description="Correlation ID propagated from AIRequest")
    schema_version: str = Field(description="Version of the JSON response schema")
    model: str = Field(description="Model identifier that resolved the response")
    completion: str = Field(description="Raw string output text from Claude")
    parsed_json: Optional[Dict[str, Any]] = Field(default=None, description="Parsed structured output")
    raw_response: Any = Field(default=None, description="Raw Anthropic response structure")
    token_usage: TokenUsage = Field(description="Token budget usage and metrics summary")
    execution_time: float = Field(description="Time elapsed during API invocation in seconds")
    success: bool = Field(description="Flag indicating if the call completed successfully")
    validation_status: str = Field(description="Status: VALIDATED, MALFORMED_JSON, SCHEMA_MISMATCH, UNVALIDATED")
    error: Optional[str] = Field(default=None, description="Validation or execution error message")
